---
# vars file for varnish
varnish_vars_port: 6081

varnish_vars_default_vcl:
  host: '127.0.0.1'
  port: '8080'

varnish_vars_vcl_backend_response:
  beresp:
    ttl: '10s'
    grace: '1h'

# Variables Private

_varnish_dependences:
  - 'apt-transport-https'

_varnish_url:
  key: 'https://repo.varnish-cache.org/ubuntu/GPG-key.txt'

_varnish_path: '/etc/varnish'

_varnish_package_name: 'varnish'

_varnish_source_templates:
  - src: "varnish-cache.list.j2"
    dest: "/etc/apt/sources.list.d/varnish-cache.list"

_varnish_post_templates:
  - src: "varnish.j2"
    dest: "/etc/default/varnish"
  - src: "default.vcl.j2"
    dest: "{{ _varnish_path }}/default.vcl"
